name: flow_builder
description: Flutter Flows made easy! A Flutter package which simplifies flows with a flexible, declarative API.
version: 0.0.3
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
